# Universe Full Configuration
# Generated: 2026-01-29T05:18:05.178935
# Total US Stocks: 501
# Total Japan Stocks: 233
# Total ETFs: 119
# Total Forex Pairs: 37
# Total Crypto: 15

universe:
  us_stocks:
    enabled: true
    description: S&P 500 constituents
    count: 501
    tickers:
    - A
    - AAL
    - AAPL
    - ABBV
    - ABNB
    - ABT
    - ACGL
    - ACN
    - ADBE
    - ADI
    - ADM
    - ADP
    - ADSK
    - AEE
    - AEP
    - AES
    - AFL
    - AIG
    - AIZ
    - AJG
    - AKAM
    - ALB
    - ALGN
    - ALL
    - ALLE
    - AMAT
    - AMCR
    - AMD
    - AME
    - AMGN
    - AMP
    - AMT
    - AMZN
    - ANET
    - ANSS
    - AON
    - AOS
    - APA
    - APD
    - APH
    - APTV
    - ARE
    - ATO
    - AVB
    - AVGO
    - AVY
    - AWK
    - AXON
    - AXP
    - AZO
    - BA
    - BAC
    - BALL
    - BAX
    - BBWI
    - BBY
    - BDX
    - BEN
    - BF-B
    - BG
    - BIIB
    - BIO
    - BK
    - BKNG
    - BKR
    - BLDR
    - BLK
    - BMY
    - BR
    - BRK-B
    - BRO
    - BSX
    - BWA
    - BX
    - BXP
    - C
    - CAG
    - CAH
    - CARR
    - CAT
    - CB
    - CBOE
    - CBRE
    - CCI
    - CCL
    - CDNS
    - CDW
    - CE
    - CEG
    - CF
    - CFG
    - CHD
    - CHRW
    - CHTR
    - CI
    - CINF
    - CL
    - CLX
    - CMA
    - CMCSA
    - CME
    - CMG
    - CMI
    - CMS
    - CNC
    - CNP
    - COF
    - COO
    - COP
    - COR
    - COST
    - CPAY
    - CPB
    - CPRT
    - CPT
    - CRL
    - CRM
    - CRWD
    - CSCO
    - CSGP
    - CSX
    - CTAS
    - CTLT
    - CTRA
    - CTSH
    - CTVA
    - CVS
    - CVX
    - D
    - DAL
    - DAY
    - DD
    - DE
    - DECK
    - DFS
    - DG
    - DGX
    - DHI
    - DHR
    - DIS
    - DLR
    - DLTR
    - DOC
    - DOV
    - DOW
    - DPZ
    - DRI
    - DTE
    - DUK
    - DVA
    - DVN
    - DXCM
    - EA
    - EBAY
    - ECL
    - ED
    - EFX
    - EG
    - EIX
    - EL
    - ELV
    - EMN
    - EMR
    - ENPH
    - EOG
    - EPAM
    - EQIX
    - EQR
    - EQT
    - ERIE
    - ES
    - ESS
    - ETN
    - ETR
    - EVRG
    - EW
    - EXC
    - EXPD
    - EXPE
    - EXR
    - F
    - FANG
    - FAST
    - FCX
    - FDS
    - FDX
    - FE
    - FFIV
    - FI
    - FICO
    - FIS
    - FITB
    - FLT
    - FMC
    - FOX
    - FOXA
    - FRT
    - FSLR
    - FTNT
    - FTV
    - GD
    - GDDY
    - GE
    - GEHC
    - GEN
    - GEV
    - GILD
    - GIS
    - GL
    - GLW
    - GM
    - GNRC
    - GOOG
    - GOOGL
    - GPC
    - GPN
    - GRMN
    - GS
    - GWW
    - HAL
    - HAS
    - HBAN
    - HCA
    - HD
    - HES
    - HIG
    - HII
    - HLT
    - HOLX
    - HON
    - HPE
    - HPQ
    - HRL
    - HSIC
    - HST
    - HSY
    - HUBB
    - HUM
    - HWM
    - IBM
    - ICE
    - IDXX
    - IEX
    - IFF
    - INCY
    - INTC
    - INTU
    - INVH
    - IP
    - IPG
    - IQV
    - IR
    - IRM
    - ISRG
    - IT
    - ITW
    - J
    - JBHT
    - JBL
    - JCI
    - JKHY
    - JNJ
    - JNPR
    - JPM
    - K
    - KDP
    - KEY
    - KEYS
    - KHC
    - KIM
    - KKR
    - KLAC
    - KMB
    - KMI
    - KMX
    - KO
    - KR
    - L
    - LDOS
    - LEN
    - LH
    - LHX
    - LIN
    - LKQ
    - LLY
    - LMT
    - LNT
    - LOW
    - LRCX
    - LULU
    - LUV
    - LVS
    - LW
    - LYB
    - LYV
    - MA
    - MAA
    - MAR
    - MAS
    - MCD
    - MCHP
    - MCK
    - MCO
    - MDLZ
    - MDT
    - MET
    - META
    - MGM
    - MHK
    - MKC
    - MKTX
    - MLM
    - MMC
    - MMM
    - MNST
    - MO
    - MOH
    - MOS
    - MPC
    - MPWR
    - MRK
    - MRNA
    - MRO
    - MS
    - MSCI
    - MSFT
    - MSI
    - MTB
    - MTCH
    - MTD
    - MU
    - NCLH
    - NDAQ
    - NDSN
    - NEE
    - NEM
    - NFLX
    - NI
    - NKE
    - NOC
    - NOW
    - NRG
    - NSC
    - NTAP
    - NTRS
    - NUE
    - NVDA
    - NVR
    - NWS
    - NWSA
    - O
    - ODFL
    - OKE
    - OMC
    - 'ON'
    - ORCL
    - ORLY
    - OTIS
    - OXY
    - PANW
    - PARA
    - PAYC
    - PAYX
    - PCAR
    - PCG
    - PEG
    - PEP
    - PFE
    - PFG
    - PG
    - PGR
    - PH
    - PHM
    - PKG
    - PLD
    - PLTR
    - PM
    - PNC
    - PNR
    - PNW
    - PODD
    - POOL
    - PPG
    - PPL
    - PRU
    - PSA
    - PSX
    - PTC
    - PWR
    - PXD
    - QCOM
    - QRVO
    - RCL
    - REG
    - REGN
    - RF
    - RJF
    - RL
    - RMD
    - ROK
    - ROL
    - ROP
    - ROST
    - RSG
    - RTX
    - SBAC
    - SBUX
    - SCHW
    - SHW
    - SJM
    - SLB
    - SMCI
    - SNA
    - SNPS
    - SO
    - SOLV
    - SPG
    - SPGI
    - SRE
    - STE
    - STLD
    - STT
    - STX
    - STZ
    - SWK
    - SWKS
    - SYF
    - SYK
    - SYY
    - T
    - TAP
    - TDG
    - TDY
    - TECH
    - TEL
    - TER
    - TFC
    - TFX
    - TGT
    - TJX
    - TMO
    - TMUS
    - TPR
    - TRGP
    - TRMB
    - TROW
    - TRV
    - TSCO
    - TSLA
    - TSN
    - TT
    - TTWO
    - TXN
    - TXT
    - TYL
    - UAL
    - UBER
    - UDR
    - UHS
    - ULTA
    - UNH
    - UNP
    - UPS
    - URI
    - USB
    - V
    - VFC
    - VICI
    - VLO
    - VLTO
    - VMC
    - VRSK
    - VRSN
    - VRTX
    - VST
    - VTR
    - VTRS
    - VZ
    - WAB
    - WAT
    - WBA
    - WBD
    - WDC
    - WEC
    - WELL
    - WFC
    - WM
    - WMB
    - WMT
    - WRB
    - WST
    - WTW
    - WY
    - WYNN
    - XEL
    - XOM
    - XYL
    - YUM
    - ZBH
    - ZBRA
    - ZTS
  japan_stocks:
    enabled: true
    description: Nikkei 225 constituents
    suffix: .T
    count: 233
    tickers:
    - '1332'
    - '1333'
    - '1605'
    - '1721'
    - '1801'
    - '1802'
    - '1803'
    - '1808'
    - '1812'
    - '1925'
    - '1928'
    - '1963'
    - '2002'
    - '2269'
    - '2282'
    - '2413'
    - '2432'
    - '2501'
    - '2502'
    - '2503'
    - '2531'
    - '2768'
    - '2801'
    - '2802'
    - '2871'
    - '2914'
    - '3086'
    - '3099'
    - '3101'
    - '3103'
    - '3105'
    - '3289'
    - '3382'
    - '3401'
    - '3402'
    - '3405'
    - '3407'
    - '3436'
    - '3861'
    - '3863'
    - '4004'
    - '4005'
    - '4021'
    - '4042'
    - '4043'
    - '4061'
    - '4063'
    - '4151'
    - '4183'
    - '4188'
    - '4208'
    - '4272'
    - '4324'
    - '4452'
    - '4502'
    - '4503'
    - '4506'
    - '4507'
    - '4519'
    - '4523'
    - '4543'
    - '4568'
    - '4578'
    - '4631'
    - '4661'
    - '4689'
    - '4704'
    - '4751'
    - '4755'
    - '4901'
    - '4902'
    - '4911'
    - '5019'
    - '5020'
    - '5101'
    - '5108'
    - '5201'
    - '5202'
    - '5214'
    - '5232'
    - '5233'
    - '5301'
    - '5332'
    - '5333'
    - '5401'
    - '5406'
    - '5411'
    - '5541'
    - '5631'
    - '5703'
    - '5706'
    - '5707'
    - '5711'
    - '5713'
    - '5714'
    - '5801'
    - '5802'
    - '5803'
    - '5901'
    - '6098'
    - '6103'
    - '6113'
    - '6178'
    - '6273'
    - '6301'
    - '6302'
    - '6305'
    - '6326'
    - '6361'
    - '6367'
    - '6471'
    - '6472'
    - '6473'
    - '6501'
    - '6502'
    - '6503'
    - '6504'
    - '6506'
    - '6645'
    - '6674'
    - '6701'
    - '6702'
    - '6703'
    - '6724'
    - '6752'
    - '6753'
    - '6758'
    - '6762'
    - '6770'
    - '6841'
    - '6857'
    - '6861'
    - '6902'
    - '6952'
    - '6954'
    - '6971'
    - '6976'
    - '6981'
    - '6988'
    - '7003'
    - '7004'
    - '7011'
    - '7012'
    - '7013'
    - '7180'
    - '7186'
    - '7201'
    - '7202'
    - '7203'
    - '7205'
    - '7211'
    - '7261'
    - '7267'
    - '7269'
    - '7270'
    - '7272'
    - '7731'
    - '7733'
    - '7735'
    - '7751'
    - '7752'
    - '7762'
    - '7832'
    - '7911'
    - '7912'
    - '7951'
    - '8001'
    - '8002'
    - '8015'
    - '8028'
    - '8031'
    - '8035'
    - '8053'
    - '8058'
    - '8233'
    - '8252'
    - '8253'
    - '8267'
    - '8303'
    - '8304'
    - '8306'
    - '8308'
    - '8309'
    - '8316'
    - '8331'
    - '8354'
    - '8355'
    - '8411'
    - '8591'
    - '8601'
    - '8604'
    - '8628'
    - '8630'
    - '8697'
    - '8725'
    - '8750'
    - '8766'
    - '8795'
    - '8801'
    - '8802'
    - '8804'
    - '8830'
    - '9001'
    - '9005'
    - '9007'
    - '9008'
    - '9009'
    - '9020'
    - '9021'
    - '9022'
    - '9062'
    - '9064'
    - '9101'
    - '9104'
    - '9107'
    - '9202'
    - '9301'
    - '9412'
    - '9432'
    - '9433'
    - '9434'
    - '9501'
    - '9502'
    - '9503'
    - '9531'
    - '9532'
    - '9602'
    - '9613'
    - '9681'
    - '9735'
    - '9766'
    - '9983'
    - '9984'
  etfs:
    enabled: true
    description: Global ETFs by category
    categories:
      equity_us:
      - SPY
      - QQQ
      - IWM
      - VTI
      - VOO
      - IVV
      - DIA
      - RSP
      - VUG
      - VTV
      - IWF
      - IWD
      - IJH
      - IJR
      - MDY
      - VB
      equity_sector:
      - XLF
      - XLK
      - XLE
      - XLV
      - XLI
      - XLY
      - XLP
      - XLU
      - XLB
      - XLRE
      - XLC
      - VGT
      - VHT
      - VFH
      - VIS
      - VCR
      - VDC
      - VPU
      - VAW
      - VNQ
      bonds:
      - TLT
      - IEF
      - SHY
      - TIP
      - LQD
      - HYG
      - JNK
      - BND
      - AGG
      - VCIT
      - VCSH
      - GOVT
      - MUB
      - EMB
      - BNDX
      - IAGG
      commodity:
      - GLD
      - SLV
      - IAU
      - SGOL
      - GDX
      - GDXJ
      - USO
      - BNO
      - UNG
      - DBA
      - DBC
      - PDBC
      - GSG
      international:
      - EFA
      - EEM
      - VEU
      - IEMG
      - VWO
      - IEFA
      - ACWI
      - ACWX
      - VEA
      - IXUS
      - SCZ
      - VSS
      - FM
      - VT
      real_estate:
      - VNQ
      - VNQI
      - IYR
      - SCHH
      - RWR
      - REET
      - REM
      - MORT
      thematic:
      - ARKK
      - ARKG
      - ARKW
      - ARKF
      - ARKQ
      - ICLN
      - TAN
      - QCLN
      - LIT
      - BOTZ
      - ROBO
      - HACK
      - SKYY
      - CLOU
      - WCLD
      - IGV
      volatility:
      - VXX
      - UVXY
      - SVXY
      - VIXY
      leveraged:
      - TQQQ
      - SQQQ
      - UPRO
      - SPXU
      - TNA
      - TZA
      - SOXL
      - SOXS
      - LABU
      - LABD
      - FAS
      - FAZ
  forex:
    enabled: true
    description: Currency pairs
    pairs:
      major:
      - USDJPY=X
      - EURUSD=X
      - GBPUSD=X
      - AUDUSD=X
      - USDCHF=X
      - USDCAD=X
      - NZDUSD=X
      cross:
      - EURJPY=X
      - GBPJPY=X
      - EURGBP=X
      - AUDJPY=X
      - CADJPY=X
      - CHFJPY=X
      - NZDJPY=X
      - EURAUD=X
      - EURCHF=X
      - EURNZD=X
      - EURCAD=X
      - GBPAUD=X
      - GBPCHF=X
      - GBPCAD=X
      - GBPNZD=X
      - AUDNZD=X
      - AUDCAD=X
      - AUDCHF=X
      emerging:
      - USDMXN=X
      - USDZAR=X
      - USDTRY=X
      - USDBRL=X
      - USDCNY=X
      - USDINR=X
      - USDKRW=X
      - USDSGD=X
      - USDHKD=X
      - USDTHB=X
      - USDMYR=X
      - USDIDR=X
  crypto:
    enabled: false
    description: Cryptocurrency pairs (disabled by default)
    tickers:
    - BTC-USD
    - ETH-USD
    - BNB-USD
    - XRP-USD
    - ADA-USD
    - SOL-USD
    - DOGE-USD
    - DOT-USD
    - AVAX-USD
    - MATIC-USD
    - LINK-USD
    - UNI-USD
    - ATOM-USD
    - LTC-USD
    - ETC-USD
presets:
  us_large_cap:
    description: US large cap stocks only
    include:
    - us_stocks
    max_assets: 100
  diversified_etf:
    description: Diversified ETF portfolio
    include:
    - etfs.equity_us
    - etfs.bonds
    - etfs.commodity
    - etfs.international
  global_multi_asset:
    description: Global multi-asset universe
    include:
    - us_stocks
    - etfs
    - forex
    exclude:
    - etfs.leveraged
    - etfs.volatility
  japan_focus:
    description: Japan-focused universe
    include:
    - japan_stocks
    - etfs.international
filters:
  min_market_cap: null
  min_avg_volume: 100000
  min_price: 5.0
  max_spread_pct: 1.0
  exclude_otc: true
  exclude_adr: false
